# To demo this pipeline:
# 1. Deploy the existing solution to Azure
# 2. Update the `KeyVaultName` in this pipeline file and commit changes
# 3. Create a new pipeline in Azure DevOps and select this file, then run it

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'spn-geo-location-development'
    KeyVaultName: 'kvdemoado'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
    echo This task will output the secret but it will be masked:
    echo $(my-super-secret)
  displayName: 'Output secrets (but masked)'